dubbo:
   application:
     qos-enable: false
   registry:
        id: zookeeper
        address: zookeeper://120.24.95.233:8084
   protocol:
        id: dubbo
        name: dubbo
        serialization: kryo
service:
   version:
       v1: 1.0.0