spring:
  redis:
     # Redis数据库索引（默认为0）
       database: 0
       # Redis服务器地址
       host: 120.24.95.233
       # Redis服务器连接端口
       port: 8083
       # Redis服务器连接密码（默认为空）
       password:
       lettuce:
         pool:
         # 连接池最大连接数（使用负值表示没有限制）
           max-active: 8
           max-idle: 8
           # 连接池最大阻塞等待时间（使用负值表示没有限制）
           max-wait: -1ms
           min-idle: 0
       timeout: 5000